import  numpy as np
import  time
import  matplotlib.pyplot as plt
time1 = time.clock()
train_X = np.load(r"CNNData\train_X1.npy")
train_Y = np.load(r"CNNData\train_Y1.npy")
test_X = np.load(r"CNNData\test_X1.npy")
test_Y = np.load(r"CNNData\test_Y1.npy")
print(train_X.shape)
print(train_Y.shape)
print(train_X[0])
print(train_Y[0])
print(test_X.shape)
print(test_Y.shape)
print(test_X[0])
print(test_Y[0])
time2 =time.clock()
plt.imshow(train_X[2],cmap='gray')
plt.show()
print(time2-time1)
